export const ITEMS={
    VIEW_ITEMS:' VIEW_ITEMS',
    DELETE_ITVIEW_ITEMS:' DELETE_ITEMS',
    CHANGE_ITEMS_NAME:'CHANGE_ITEMS_NAME',
    CHANGE_ITEM_NICKNAME:'CHANGE_ITEM_NICKNAME',
    CHANGE_ITEM_CATEGORY:'CHANGE_ITEM_CATEGORY',
    CHANGE_RESTUARANT:'CHANGE_RESTUARANT',
    CHANGE_ITEM_REGULAR_PRICE:'CHANGE_ITEM_REGULAR_PRICE',
    CHANGE_ITEM_NEW_PRICE:'CHANGE_ITEM_NEW_PRICE',
    CHANGE_ITEM_DISCOUNT_RATE:'CHANGE_ITEM_DISCOUNT_RATE',
    CHANGE_ITEM_DESCRIPTION:'CHANGE_ITEM_DESCRIPTION',
   CHANGE_ITEM_IMAGES1:'CHANGE_ITEM_IMAGES1',
   CHANGE_ITEM_IMAGES2:'CHANGE_ITEM_IMAGES2',
    SAVE_ITEMS_CHANGES:'SAVE_ITEMS_CHANGES',
    GET_ITEMS_DATA:'GET_ITEMS_DATA',
    SAVE_ITEMS_CHANGES:'SAVE_ITEMS_CHANGES'
            
};