export const LOGIN={
 
    CHANGE_EMAIL:'CHANGE_EMAIL',
   
    CHANGE_PASSWORD:'CHANGE_PASSWORD',
    SUBMITLOGINDATA:'SUBMITLOGINDATA',
    GET_RESTUARANT_DATA:'GET_RESTUARANT_DATA',
    GET_RESTUARANT_DATA_API:'GET_RESTUARANT_DATA_API',
    LOGIN_USER_SUCCESSFUL:'LOGIN_USER_SUCCESSFUL',
    LOGIN_USER_ERROR:'LOGIN_USER_ERROR' ,
    LOGIN_USER_ERROR_CHANGE:'LOGIN_USER_ERROR_CHANGE' ,
};