export const CATEGORY={
    VIEW_RESTUARANTS:' VIEW_RESTUARANTS',
    DELETE_RESTUARANTS:' DELETE_RESTUATANT',
    CHANGE_CATEGORY_NAME:'CHANGE_CATEGORY_NAME',
    CHANGE_CATEGORY_IMAGES:'CHANGE_CATEGORY_IMAGES',
    SAVE_CATEGORY_CHANGES:'SAVE_CATEGORY_CHANGES',
    GET_CATEGORY_DATA:'GET_CATEGORY_DATA'
            
};